# Generated by Django 4.1.7 on 2023-04-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_remove_articlecategory_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="article/%Y%m%d"),
        ),
    ]
