# Generated by Django 4.1.7 on 2023-04-04 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_article_avatar"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="avatar",),
    ]
