# Generated by Django 4.1.7 on 2023-04-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecategory",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
