# Generated by Django 4.1.7 on 2023-04-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0007_alter_articlecategory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecategory",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="article.articlecategory",
            ),
        ),
    ]
